### PR TITLE
notes in the comment area

### PR DESCRIPTION
**Pull request by tbranyen**
Reworked bindings to use latest upskirt version including html src instead of xhtml.  Using fast buffer now instead of string return.  Using std::string instad of passing around buffers.

### CODE REVIEW

**Comment by tbranyen** [comment]
oh yeah bumped the version num too

**Comment by benmills** [comment]
Hey thanks for the pull request! It looks good but I've run into an issue in the past where some extra characters are added on to the end of long markdown files. Try building your fork and then edit the example to uncomment the bottom example and change it to look like this:

``` javascript
//Open a file and parse it                          
fs.readFile('README.mkd', function (err, data) {    
  markdown.toHtml(data.toString(), function (html) {
    sys.puts(html);                                 
  });                                               
});                                                 
```

Notice that I changed `toHtml(data` to `toHtml(data.toString()` from what is currently in the repo.

**Comment by benmills** [comment]
It looks like if I set and pass `sr->out_size = ob->size;` inside `ToHtmlAsync` and use that in `ToHtml_After` in place of `sr->out.size()` I don't see the extra characters.

Is it alright to make that change or is there a better fix for this?

**Comment by tbranyen** [comment]
Hmmm. interesting that does fix it on my end as well.

**Comment by tbranyen** [comment]
Awesome, glad to see this made it in with those fixes.  Sorry I reformatted so much code xD

**Comment by benmills** [comment]
No problem at all thanks for the pull request.

**Pull request merged**
